### ISSUE TITLE
Question on import tensorflow as tf

### ISSUE THREAD

**Issue by cclauss** [tensorflow/tpu-demos#24]
@frankchn Normally in the code, I see `import tensorflow as tf` but https://github.com/tensorflow/tpu-demos/blob/master/cloud_tpu/diagnostics/diagnostics.py#L24-L30 takes a very different approach.  What is this code in `diagnostics.py` doing that the normal approach does not do?  Thanks.

Also a similar question on importing `slim` in this way https://github.com/tensorflow/tpu-demos/blob/master/cloud_tpu/models/inception_v2/inception_v2.py#L28

**Comment by frankchn** [comment]
Ah, that is actually an error in transforming our internal code to external code. I'll get that fixed.

**Comment by frankchn** [comment]
This should be fixed with the latest changes.
