### ISSUE TITLE
Attempt to access beyond input size: 4 >= 4

### ISSUE THREAD

**Issue by ryanjay0** [tensorflow/tpu-demos#45]
https://github.com/tensorflow/tpu-demos/blob/cb18fe2a4bacf4c8ef7685aebfbffb4550d5e938/cloud_tpu/models/resnet_garden/resnet_main.py#L204

I can't get parallel_interleave to work here. It gives this error:

```
InvalidArgumentError (see above for traceback): Attempt to access beyond input size: 4 >= 4
	In ParallelInterleaveDataset = ParallelInterleaveDataset[Targuments=[], f=tf_map_func_c72e772a[], output_shapes=[[]], output_types=[DT_STRING]](RepeatDataset:handle:0, ParallelInterleaveDataset/input_pipeline_task0/cycle_length:output:0, ParallelInterleaveDataset/input_pipeline_task0/block_length:output:0, ParallelInterleaveDataset/input_pipeline_task0/sloppy:output:0)
	 [[Node: input_pipeline_task0/OneShotIterator = OneShotIterator[container="", dataset_factory=_make_dataset_737011ca[], output_shapes=[[1024,224,224,3], [1024,1001]], output_types=[DT_FLOAT, DT_FLOAT], shared_name="", _device="/job:tpu_worker/replica:0/task:0/device:CPU:0"]()]]
```

The ImageNet data is coming from gcs and it's definitely accessible.
It works fine if I replace the line with interleave (no parallel) and remove the apply, but I'm afraid that might slow it down significantly. 

Note: my gpu version of this code is happy with parallel_interleave.

**Comment by frankchn** [comment]
Are you using the same code and settings on GPU and Cloud TPUs?

**Comment by frankchn** [comment]
We are also interested in what version of Cloud TPU and TensorFlow you are using. It will be great if you can start a new Cloud TPU and install the latest nightly of TensorFlow (from `pip install tf-nightly`) with default batch sizes and see if you can isolate the problem.

**Comment by ryanjay0** [comment]
We are using the latest version of tf and the cloud tpu demo code. On the phone with Arhaan and Marcos today they were able to reproduce the bug immediately.

Sent from Yahoo Mail on Android 
 
  On Wed, Jan 3, 2018 at 14:51, Frank Chen<notifications@github.com> wrote:   
We are also interested in what version of Cloud TPU and TensorFlow you are using. It will be great if you can start a new Cloud TPU and install the latest nightly of TensorFlow (from pip install tf-nightly) with default batch sizes and see if you can isolate the problem.

**Comment by saeta** [comment]
Hey @ryanjay0 

Sorry about the failure. The underlying issue is that https://github.com/tensorflow/tensorflow/commit/76db97fe3961651617371902a1a623df61f9ed81 changed the definition of parallel interleave. While it's backwards compatible from the Python API, it is not backwards compatible at the RPC level. Alas, RPC incompatibilities are a known issue without a good short-term fix, and that's why the Cloud TPU nightly builds are not stable and don't come with any guarantees.

I've confirmed this morning that if you create a new Cloud TPU, and use a fresh install of TF-nightly, you shouldn't encounter this issue. Once TF-1.5 lands in the next few weeks, I strongly recommend switching to that, as the stable release won't encounter these issues.

Thank you very much for trying out Cloud TPUs, and please do file issues you encounter, and reopen if this is still an issue!

All the best,
-Brennan

**Comment by ryanjay0** [comment]
Unfortunately that didn't work and we get the exact same issue with a brand new instance, tpu-resource, and newly cloned tpu-demos repo. Exact same error. Maybe I can just revert that commit and recompile the master.

**Comment by sb2nov** [comment]
@ryanjay0 can you specify what version of Tensorflow is installed on your GCE VM. And also try installing the TF nightly and check if that resolves this issue.

**Comment by ryanjay0** [comment]
We got past that error by pip installing tf-nightly. Creating a new instance and tpu-resource with the tf-nightly parameter wasn't enough. 

Unfortunately we are still having an issue. The error is now "DataLossError (see above for traceback): corrupted record at 0"

Perhaps we need to recreate the tfrecords to be compatible with the new tensorflow nightly, but it was working fine without parallel interleave. We are working with Arhaan also to resolve this but if you have any suggestions i'd be happy to try them.


TF version. 1.5.0-dev20180103

**Comment by Mistobaan** [comment]
Got same error using the ml-engine job system with runtime-version HEAD 

```
gcloud ml-engine jobs submit training $JOB_NAME \
--staging-bucket $STAGING_BUCKET \
--runtime-version HEAD \
--scale-tier BASIC_TPU \
--module-name resnet_garden.resnet_main \
--package-path resnet_garden/ \
--region $REGION \
-- --data_dir=gs://cloudtpu-imagenet-data/train --model_dir=$OUTPUT_PATH --train_steps=5000
```

**Comment by saeta** [comment]
@ryanjay0 I believe we've fixed the issue with the nightly GCE images, so new nightly GCE VMs should not encounter the "Attempt to access beyond input size" error any further. As for the `DataLossError (see above for traceback): corrupted record at 0` error, I'd need more context / logs to be sure, but it seems like your error is generated from https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/lib/io/record_reader.cc#L114 (or similar lines in the same file). Is it possible that you have an extra file in your data directory? (e.g. Did you put your model directory in the same location as your data directory?)

@Mistobaan As a short-term fallback while the updated builds propagate through to CMLE, you can switch from parallel interleave to standard interleave (at a runtime performance cost). Once TF-1.5 lands on Cloud TPUs and CMLE, you shouldn't encounter any of these issues.

Please do re-open this issue if the issues aren't resolved by Tuesday morning. Thanks!

**Comment by ryanjay0** [comment]
It works. Thanks everyone for the advice.
